name: GPT Translate
 
on:
  issue_comment:
    types: [created]
 
jobs:
  gpt_translate:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run GPT Translate
        if: |
          contains(github.event.comment.body, '/gt')
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-2024-11-20'

      - name: Create Pull Request
        if: |
          contains(github.event.comment.body, '/gt') && 
          steps.translate.conclusion == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add translation files via GPT Translate"
          title: "🌐 Auto-translation: New translation files"
          body: |
            ## 🤖 Automated Translation
            
            This pull request was automatically created after running GPT Translate.
            
            ### Changes:
            - Added new translation files
            - Updated existing translations
            
            ### Triggered by:
            Comment: ${{ github.event.comment.html_url }}
            User: @${{ github.event.comment.user.login }}
            
            ---
            *This PR was automatically generated by GitHub Actions*
          branch: translation-${{ github.run_number }}
          delete-branch: true
          assignees: ${{ github.event.comment.user.login }}
          reviewers: ${{ github.event.comment.user.login }}
          labels: |
            translation
            automated
            gpt-translate
