name: Auto-Translate Documentation

on:
  push:
    paths:
      - 'ru/**'  # Запуск при изменениях в папке ru

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-rus

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt
          pip install sentencepiece

      - name: Run translation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/translate.py --source_dir ./ru --target_dir ./en --glossary scripts/glossary.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add en/
          git diff --staged --quiet || git commit -m "Auto-translate: update English version [skip ci]"
          git push
