name: Translate GitBook Content

on:
  push:
    branches: [ main ]
    paths: [ 'ru/SUMMARY.md' ]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Translate Content
      uses: ./.github/actions/gitbook-translator
      with:
        source_language: 'ru'
        target_language: 'en'
        translator_api_key: ${{ secrets.AZURE_TRANSLATOR_API_KEY }}
