name: Auto-Translate Documentation

on:
  push:
    paths:
      - 'ru/**'  # Запуск при изменениях в папке ru
      - 'scripts/**'  # Запуск при изменении скриптов
    branches:
      - main
      - master
  pull_request:
    paths:
      - 'ru/**'
      - 'scripts/**'
  workflow_dispatch:  # Ручной запуск
    inputs:
      force_retranslate:
        description: 'Force retranslation of all files'
        required: false
        default: 'false'
        type: boolean
      translation_method:
        description: 'Translation method'
        required: false
        default: 'ai'
        type: choice
        options:
        - 'ai'
        - 'simple'

env:
  PYTHON_VERSION: '3.11'
  CACHE_VERSION: 'v1'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.changes.outputs.ru }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ru:
              - 'ru/**'
            scripts:
              - 'scripts/**'

      - name: Generate file matrix
        id: matrix
        if: steps.changes.outputs.ru == 'true' || github.event.inputs.force_retranslate == 'true'
        run: |
          if [[ "${{ github.event.inputs.force_retranslate }}" == "true" ]]; then
            echo "Force retranslation enabled"
            files=$(find ru -name "*.md" -o -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" | head -50)
          else
            # Получаем измененные файлы
            files=$(git diff --name-only HEAD~1 HEAD | grep -E '^ru/.*\.(md|png|jpg|jpeg)$' | head -20)
          fi
          
          if [ -z "$files" ]; then
            echo "matrix=[]" >> $GITHUB_OUTPUT
          else
            matrix=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
          fi

  translate:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true' || github.event.inputs.force_retranslate == 'true'
    
    strategy:
      fail-fast: false
      max-parallel: 3
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Cache system dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            /usr/share/tesseract-ocr
            /var/cache/apt
          key: system-deps-${{ env.CACHE_VERSION }}-${{ runner.os }}

      - name: Install system dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tesseract-ocr \
            tesseract-ocr-rus \
            tesseract-ocr-eng \
            libtesseract-dev \
            libopencv-dev \
            python3-opencv

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ env.CACHE_VERSION }}-${{ hashFiles('scripts/requirements.txt') }}
          restore-keys: |
            pip-${{ env.CACHE_VERSION }}-

      - name: Create requirements.txt if not exists
        run: |
          if [ ! -f scripts/requirements.txt ]; then
            mkdir -p scripts
            cat > scripts/requirements.txt << EOF
          torch>=1.13.0
          transformers>=4.21.0
          sentencepiece>=0.1.97
          accelerate>=0.20.0
          Pillow>=9.0.0
          opencv-python>=4.7.0
          pytesseract>=0.3.10
          numpy>=1.21.0
          packaging
          EOF
          fi

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -r scripts/requirements.txt
          # Установка дополнительных зависимостей для CI
          pip install pytest pytest-cov

      - name: Cache Hugging Face models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: hf-models-${{ env.CACHE_VERSION }}-${{ hashFiles('scripts/translate.py') }}
          restore-keys: |
            hf-models-${{ env.CACHE_VERSION }}-

      - name: Validate scripts
        run: |
          python -m py_compile scripts/translate.py
          if [ -f scripts/image_processor.py ]; then
            python -m py_compile scripts/image_processor.py
          fi

      - name: Create glossary if not exists
        run: |
          if [ ! -f scripts/glossary.json ]; then
            mkdir -p scripts
            cat > scripts/glossary.json << 'EOF'
          {
            "API": "API",
            "Docker": "Docker",
            "Kubernetes": "Kubernetes",
            "микросервис": "microservice",
            "контейнер": "container",
            "развертывание": "deployment",
            "мониторинг": "monitoring",
            "логирование": "logging",
            "балансировщик нагрузки": "load balancer",
            "база данных": "database"
          }
          EOF
          fi

      - name: Run translation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          TRANSLATION_METHOD: ${{ github.event.inputs.translation_method || 'ai' }}
        run: |
          set -e
          
          # Определяем параметры запуска
          FORCE_FLAG=""
          if [[ "${{ github.event.inputs.force_retranslate }}" == "true" ]]; then
            FORCE_FLAG="--force"
          fi
          
          AI_FLAG=""
          if [[ "$TRANSLATION_METHOD" == "simple" ]]; then
            AI_FLAG="--no-ai"
          fi
          
          echo "Starting translation process..."
          echo "Force retranslation: ${{ github.event.inputs.force_retranslate }}"
          echo "Translation method: $TRANSLATION_METHOD"
          
          # Запускаем перевод с обработкой ошибок
          python scripts/translate.py \
            --source_dir ./ru \
            --target_dir ./en \
            --glossary scripts/glossary.json \
            --verbose \
            $FORCE_FLAG \
            $AI_FLAG || {
              echo "Translation failed, but continuing with available results"
              exit_code=$?
              echo "::warning::Translation completed with errors (exit code: $exit_code)"
            }

      - name: Check translation results
        run: |
          echo "Translation results:"
          if [ -d ./en ]; then
            find ./en -name "*.md" -o -name "*.png" -o -name "*.jpg" | head -10
            echo "Total files created: $(find ./en -type f | wc -l)"
          else
            echo "No translation output directory found"
          fi

      - name: Setup Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: check-changes
        run: |
          git add en/
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff --staged --name-only
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          # Создаем более информативное сообщение коммита
          commit_msg="docs: auto-translate documentation"
          
          if [[ "${{ github.event.inputs.force_retranslate }}" == "true" ]]; then
            commit_msg="$commit_msg (forced retranslation)"
          fi
          
          if [[ "${{ github.event.inputs.translation_method }}" == "simple" ]]; then
            commit_msg="$commit_msg [simple mode]"
          fi
          
          # Добавляем информацию об измененных файлах
          changed_files=$(git diff --staged --name-only | wc -l)
          commit_msg="$commit_msg - $changed_files files updated"
          
          commit_msg="$commit_msg [skip ci]"
          
          git commit -m "$commit_msg"
          git push

      - name: Create summary
        if: always()
        run: |
          echo "## Translation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Source directory**: ru/" >> $GITHUB_STEP_SUMMARY
          echo "- **Target directory**: en/" >> $GITHUB_STEP_SUMMARY
          echo "- **Translation method**: ${{ github.event.inputs.translation_method || 'ai' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Force retranslation**: ${{ github.event.inputs.force_retranslate || 'false' }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -d ./en ]; then
            total_files=$(find ./en -type f | wc -l)
            md_files=$(find ./en -name "*.md" | wc -l)
            img_files=$(find ./en -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" | wc -l)
            
            echo "- **Total files processed**: $total_files" >> $GITHUB_STEP_SUMMARY
            echo "- **Markdown files**: $md_files" >> $GITHUB_STEP_SUMMARY
            echo "- **Image files**: $img_files" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [[ "${{ steps.check-changes.outputs.has_changes }}" == "true" ]]; then
            echo "- **Status**: ✅ Changes committed and pushed" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status**: ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          fi

  # Дополнительная проверка качества перевода
  quality-check:
    runs-on: ubuntu-latest
    needs: translate
    if: always() && needs.translate.result == 'success'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check translation quality
        run: |
          echo "## Quality Check Results" >> $GITHUB_STEP_SUMMARY
          
          if [ -d ./en ]; then
            # Проверяем структуру файлов
            ru_md_count=$(find ./ru -name "*.md" | wc -l)
            en_md_count=$(find ./en -name "*.md" | wc -l)
            
            echo "- **Russian MD files**: $ru_md_count" >> $GITHUB_STEP_SUMMARY
            echo "- **English MD files**: $en_md_count" >> $GITHUB_STEP_SUMMARY
            
            if [ $en_md_count -eq $ru_md_count ]; then
              echo "- **File structure**: ✅ Complete" >> $GITHUB_STEP_SUMMARY
            else
              echo "- **File structure**: ⚠️ Incomplete ($en_md_count/$ru_md_count)" >> $GITHUB_STEP_SUMMARY
            fi
            
            # Проверяем размеры файлов
            empty_files=$(find ./en -name "*.md" -empty | wc -l)
            if [ $empty_files -eq 0 ]; then
              echo "- **Empty files**: ✅ None" >> $GITHUB_STEP_SUMMARY
            else
              echo "- **Empty files**: ⚠️ Found $empty_files empty files" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "- **Status**: ❌ Translation directory not found" >> $GITHUB_STEP_SUMMARY
          fi
